const LANG_BY_ISLAND = {
    Sumatra: {
        indonesian: {
                story: "“Kami akan mengusukan lima daerah yang sudah diteliti ini kepada Menteri Agama untuk menjadi desa model kerukunan umat beragama,” ujar Ismail saat ditemui Republika.co.id usai seminar hasil penelitian di Bogor, Jumat, (1 / 11).Lima wilayah Sumatra yang masuk dalam penelitian ini, yaitu kerukunan umat beragama di Tungkal Ilir, Tanjung Jabung Barat.Kedua, kerukunan di Sipirok, Tapanuli Selatan, Sumatra Utara.Ketiga, toleransi dan kerjasama umat beragama di Desa Rawa Selapan, Kecamatan Candipuro, Lampung Selatan.Keempat, toleransi dan kerjasama umat beragama di Desa Lubuk Seberuk, Kecamatan Lempuing Jaya, Sumatra Selatan. Kelima, toleransi dan kerjasama antarumat beragama di Gampong Mulia, Kecamatan Kuta Alam, Banda Aceh.Dia menjelaskan, penelitian ini berawal dari keresahan Balitbang Kemenag terhadap isu - isu toleran dan inteleran saat ini.Karena, menurut dia, kebanyakan yang terekspos itu justru kasu - kasus yang intoleran.Karena itu, menurut dia, dengan melakukan penelitian ini, pihaknya ingin mengkonter isu - isu intoleran tersebut. “Kita di Litbang ingin mengkonter isu - isu intoleran itu dengan memunculkan wilayah - wilayah yang damai sebagai bukti bahwa Indonesia itu isunya tidak hanya intoleran saja, tapi daerah - daerah yang damai juga banyak di Indonesia,” ucap Ismail.Sementara itu, peneliti yang melakukan penelitian di Tungkal Ilir, M Agus Noorbani menjelaskan, penduduk di wilayah Tungkal Ilir sangat taat dalam mengamalkan agamanya masing - masing, sehingga mereka bisa hidup toleran dan rukun.Karena itu, menurut dia, Tungkal Ilir layak menjadi model desa kerukunan di Indonesia. “Jadi, dari yang saya dapat di lokasi penelitian, orang - orang di wilayah ini mereka orang yang beragamanya tinggi.Jadi, kekuatan iman mereka itulah yang membuat mereka hidup toleran,” jelasnya."
            },
            sundanese: {
                story: "Kami baris ngusulkeun lima wewengkon anu geus ditalungtik ka Mentri Agama pikeun dijadikeun kampung modél.\" karukunan umat beragama,” ceuk Ismail waktu dipanggihan ku Republika.co.id sanggeus seminar hasil panalungtikan di Bogor, Jumaah(1/ 11).Lima wewengkon Sumatra kaasup kana ieu panalungtikan, nya éta karukunan umat beragama di Indonésia Tungkal Ilir, Tanjung Jabung Barat.Kadua, karukunan di Sipirok, Tapanuli Selatan, Sumatera Utara.katilu, toleransi jeung gotong royong umat beragama di Désa Rawa Selapan, Kacamatan Candipuro, Lampung Kidul.Kaopat, toleransi jeung gotong royong umat beragama di Désa Lubuk Seberuk, Kacamatan Lemrub Jaya, Sumatra Kidul. Kalima, toleransi jeung gotong royong antar umat beragama di Gampong Mulia Kacamatan Kuta Alam Banda Acéh.Anjeunna nétélakeun yén ieu panalungtikan dimimitian tina kaparigelan Balitbang Kemendagri ngeunaan masalah toleran jeung intoleran. dina waktos ayeuna.Sabab, numutkeun anjeunna, kalolobaan kasus anu kakeunaan mangrupikeun kasus intoleransi.Kusabab kitu, numutkeun anjeunna, ku ngalaksanakeun ieu panalungtikan, pihakna hoyong ngalawan pasualan intoleran ieu. \"Urang di R & D hoyong nantang masalah- masalah anu teu toleran ieu ku cara ngajantenkeun daérah damai salaku bukti yen Indonesia teh lain wae masalah intoleran, tapi oge daerah damai di loba daerah Indonésia, \" ceuk Ismail. Sedengkeun panalungtik anu ngalaksanakeun panalungtikan di Tungkal Ilir, M Agus Noorbani ngajelaskeun, warga di wewengkon Tungkal Ilir kacida taat kana agamana masing - masing, sangkan aranjeunna tiasa hirup toleran sareng rukun.Ku kituna, numutkeun anjeunna, Tungkal Ilir pantes janten kampung modél harmoni di Indonésia. “Tah, tina naon anu kuring meunang di situs panalungtikan, masarakat di wewengkon ieu aranjeunna jalma anu kacida agamana.Janten, kakuatan iman aranjeunna anu ngajantenkeun aranjeunna hirup toleran.\" anjeunna ngajelaskeun."
            }
    },
    Jawa: {
        indonesian: {
            story: "Senin (27/5/2019) petang, SD Kristen Petra, Jombang, kedatangan tamu dari Madrasah Ibtidaiyah (MI) Islamiyah Desa Plosogenuk, Kecamatan Perak, Kabupaten Jombang. Mereka kemduaian bermain di lapangan sekolah sembari menunggu waktu berbuka puasa. Kemudian sejumlah siswa SD Kristen Petra mengajak para siswa MI berkeliling kompleks sekolah. Mereka diajak berkeliling untuk mengunjungi ruang kelas, taman bermain, serta mengunjungi Gereja Kristen Indonesia (GKI) yang berada di lingkungan sekolah tersebut. Waktu adzan Maghrib pun tiba. Anak-anak dari MI Islamiyah berbuka puasa bersama anak-anak dari SD Kristen Petra, SD Kristen Wijana, serta anak-anak GKJW Bongsorejo dari SDN Grogol 2. Seusai buka puasa bersama, sejumlah siswa SD Kristen dibantu para guru menyiapkan tempat untuk rombongan dari MI Islamiyah melaksanakan shalat Maghrib. Sementara siswa lain tampak melayani para siswa MI Islamiyah untuk berwudhu dengan cara memegangi selang air. “Karena di sini tidak keran air untuk fasilitas wudhu, kami minta anak anak untuk melayani wudhu dengan menggunakan selang air,” ujar Kepala SD Kristen Petra Riri Nurini Setia Ningrum. Para guru dan murid yang beragama Islam kemudian salat berjemaah di depan pintu gernag Gereja Kristen Indonesia."
        },
        sundanese: {
            story: "Senen (27/5/2019) sonten, SD Kristen Petra, Jombang, ngagaduhan tamu ti Madrasah Ibtidaiyah (MI) Islamiyah Desa Plosogenuk, Kacamatan Perak, Kabupaten Jombang. Duanana ulin ka lapang sakola bari nungguan waktu buka puasa. Lajeng sajumlah murid SD Kristen Petra nyandak murid MI sabudeureun kompleks sakola. Aranjeunna diajak nguriling nganjang ka ruang kelas, tempat ulin, jeung nganjang ka Gereja Kristen Indonesia (GKI) anu aya di lingkungan sakola. Wanci adzan Magrib datang. Barudak MI Islamiyah buka puasa jeung barudak SD Kristen Petra, SD Kristen Wijana, jeung budak GKJW Bongsorejo SD Grogol 2. Sabada buka puasa babarengan, sajumlah murid SD Kristen dibantuan ku guru-guru pikeun nyiapkeun . tempat rombongan ti MI Islamiyah ngalaksanakeun sholat maghrib. Samentara éta, santri-santri séjénna katémbong ngalayanan santri MI Islamiyah pikeun wudhu ku cara nahan selang cai. “Kusabab di dieu teu aya keran cai pikeun fasilitas wudhu, kami nitah barudak ngaladénan wudhu maké selang cai,” ceuk Kapala SD Kristen Petra Riri Nurini Setia Ningrum. Guru-guru jeung murid-murid anu beragama Islam tuluy solat babarengan di hareupeun gerbang Garéja Kristen Indonésia."
        }
    },
};

function setLang(island) {
    var story = document.getElementById("story");
    if (getCookie("language") === "indonesian") {
        story.textContent = LANG_BY_ISLAND[island].indonesian.story;
    }
    else if (getCookie("language") === "sundanese") {
        story.textContent = LANG_BY_ISLAND[island].sundanese.story;
    }
}